<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>items templates</title>
    <link href="//cdn.bootcss.com/pure/0.6.0/pure-min.css" rel="stylesheet">
    <!-- <link href="//cdn.bootcss.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet"> -->
</head>
<body>
    <h1>All Items</h1>
    <p><a href="/items/new">新增items</a></p>
    <table class="pure-table">
        <tr>
            <th>id</th>
            <th>name</th>
            <th>电子邮件</th>
            <th>地址</th>
            <th>操作</th>
        </tr>

    <?php foreach($data['items'] as $v): ?>
        <tr>
            <td><?=$v['id']?></td>
            <td><?=$v['name'] ?></td>
            <td><?=$v['email'] ?></td>
            <td><?=$v['address'] ?></td>
            <td> 
                <a href="<?=$router->pathFor('items-detail', ['id' => $v['id']])?>">浏览</a>
            </td>
        </tr>
    <?php endforeach; ?>
    </table>
</body>
</html>